#lang racket
(require "parser.rkt"
         (prefix-in stx: "syntax.rkt"))

(define (parse->string parse)
  (cond ((list? parse) (for-each (lambda (x) (parse->string x)) parse))
        ((stx:declar? parse)
         (let ((declr-list (stx:declar-declrs parse)))
           (display (list-ref (caar declr-list) (- (length (caar declr-list)) 1)))
           (display " ")
           (define (write-comma list)
             (let ((name (if (stx:array-exp? (cdar list))
                             (parse->string (cdar list))
                             `(,(cadar list))))
                   (star-list (filter (lambda (x) (eq? x '*)) (caar list))))
               (if (null? (cdr list))
                   (begin (for-each display star-list)
                          (for-each display name)
                          (display ";\n"))
                   (begin (for-each display star-list)
                          (for-each display name)
                          (printf ", ")
                          (write-comma  (cdr list))))))
           (write-comma declr-list)))
        ((stx:function-prototype? parse)
         (let ((type (stx:function-prototype-type parse))
               (name (stx:function-prototype-name parse))
               (params (stx:function-prototype-parms parse)))
           (display (list-ref type (- (length type) 1)))
           (display " ")
           (for-each display (filter (lambda (x) (eq? x '*)) type))
           (display name)
           (display "( ")
           (define (write-comma list)
             (if (null? list)
                 (display ");\n")
                 (let ((type (list-ref (caaar list) (- (length (caaar list)) 1)))
                       (name `(,(cadar list)))
                       (star-list (filter (lambda (x) (eq? x '*)) (caaar list))))
                   (begin
                     (if (null? (cdr list))
                         (begin (display type)
                                (display " ")
                                (for-each display star-list)
                                (for-each display name)
                                (display " );\n"))
                         (begin (display type)
                                (display " ")
                                (for-each display star-list)
                                (for-each display name)
                                (printf ", ")
                                (write-comma  (cdr list))))))))
           (write-comma params)))
        ((stx:function-definition? parse)
         (let ((type (stx:function-definition-type parse))
               (name (stx:function-definition-name parse))
               (params (stx:function-definition-parms parse))
               (body (stx:function-definition-body parse)))
           (display (list-ref type (- (length type) 1)))
           (display " ")
           (for-each display (filter (lambda (x) (eq? x '*)) type))
           (display name)
           (display "( ")
           (define (write-comma list)
             (if (null? list)
                 (display ")")
                 (let ((type (list-ref (caaar list) (- (length (caaar list)) 1)))
                       (name `(,(cadar list)))
                       (star-list (filter (lambda (x) (eq? x '*)) (caaar list))))
                   (begin
                     (if (null? (cdr list))
                         (begin (display type)
                                (display " ")
                                (for-each display star-list)
                                (for-each display name)
                                (display " )"))
                         (begin (display type)
                                (display " ")
                                (for-each display star-list)
                                (for-each display name)
                                (printf ", ")
                                (write-comma  (cdr list))))))))
           (write-comma params)
           (display "{\n")
           (for-each parse->string body)
           (display "}\n")))
        ((stx:if-stmt? parse)
         (display "if ( ")
         (parse->string (stx:if-stmt-test parse))
         (display " ){\n")
         (parse->string (stx:if-stmt-tbody parse))
         (display "} else {\n")
         (parse->string (stx:if-stmt-ebody parse))
         (display "}\n")
         )
        ((stx:while-stmt? parse)
         (display "while( ")
         (parse->string (stx:while-stmt-test parse))
         (display " ){\n")
         (parse->string (stx:while-stmt-body parse))
         (display "}\n"))
        ((stx:return-stmt? parse)
         (display "return ")
         (parse->string (stx:return-stmt-exp parse)))
        ((stx:array-exp? parse)
         (let ((array-name (stx:array-exp-name parse))
               (array-size (stx:array-exp-size parse)))
           (if (stx:array-exp? array-name)
               (append (parse->string array-name)
                       `(\[ ,array-size \]))
               `(,(car array-name) \[ ,array-size \]))))
        (else (printf "ここはまだできないよ！\n"))))
